version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: guardian_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guardian
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: guardian_backend
    ports:
      - "8080:8080"      # HTTP
      - "50051:50051"    # gRPC
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/guardian?sslmode=disable
    restart: unless-stopped

volumes:
  postgres_data:
