server:
  port: ":8080"
  grpc_port: ":50051"
database:
  dsn: "postgres://user:password@localhost:5432/guardian_db?sslmode=disable"

auth:
  jwt_secret: "a-very-secret-key-that-should-be-long-and-random"
