// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: guardian.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_guardian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UploadMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int32                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMessagesRequest) Reset() {
	*x = UploadMessagesRequest{}
	mi := &file_guardian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessagesRequest) ProtoMessage() {}

func (x *UploadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessagesRequest.ProtoReflect.Descriptor instead.
func (*UploadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMessagesRequest) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *UploadMessagesRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type UploadMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMessagesResponse) Reset() {
	*x = UploadMessagesResponse{}
	mi := &file_guardian_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessagesResponse) ProtoMessage() {}

func (x *UploadMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessagesResponse.ProtoReflect.Descriptor instead.
func (*UploadMessagesResponse) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMessagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int32                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_guardian_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *HeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 未来可以加入任务指令
	TaskId        string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_guardian_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_guardian_proto protoreflect.FileDescriptor

const file_guardian_proto_rawDesc = "" +
	"\n" +
	"\x0eguardian.proto\x12\bguardian\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\vChatMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"e\n" +
	"\x15UploadMessagesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x05R\aagentId\x121\n" +
	"\bmessages\x18\x02 \x03(\v2\x15.guardian.ChatMessageR\bmessages\"2\n" +
	"\x16UploadMessagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x05R\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\",\n" +
	"\x11HeartbeatResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId2T\n" +
	"\fAgentService\x12D\n" +
	"\tHeartbeat\x12\x1a.guardian.HeartbeatRequest\x1a\x1b.guardian.HeartbeatResponse2b\n" +
	"\vDataService\x12S\n" +
	"\x0eUploadMessages\x12\x1f.guardian.UploadMessagesRequest\x1a .guardian.UploadMessagesResponseB\x17Z\x15guardian/pkg/grpc/apib\x06proto3"

var (
	file_guardian_proto_rawDescOnce sync.Once
	file_guardian_proto_rawDescData []byte
)

func file_guardian_proto_rawDescGZIP() []byte {
	file_guardian_proto_rawDescOnce.Do(func() {
		file_guardian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guardian_proto_rawDesc), len(file_guardian_proto_rawDesc)))
	})
	return file_guardian_proto_rawDescData
}

var file_guardian_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_guardian_proto_goTypes = []any{
	(*ChatMessage)(nil),            // 0: guardian.ChatMessage
	(*UploadMessagesRequest)(nil),  // 1: guardian.UploadMessagesRequest
	(*UploadMessagesResponse)(nil), // 2: guardian.UploadMessagesResponse
	(*HeartbeatRequest)(nil),       // 3: guardian.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 4: guardian.HeartbeatResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_guardian_proto_depIdxs = []int32{
	5, // 0: guardian.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: guardian.UploadMessagesRequest.messages:type_name -> guardian.ChatMessage
	3, // 2: guardian.AgentService.Heartbeat:input_type -> guardian.HeartbeatRequest
	1, // 3: guardian.DataService.UploadMessages:input_type -> guardian.UploadMessagesRequest
	4, // 4: guardian.AgentService.Heartbeat:output_type -> guardian.HeartbeatResponse
	2, // 5: guardian.DataService.UploadMessages:output_type -> guardian.UploadMessagesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guardian_proto_init() }
func file_guardian_proto_init() {
	if File_guardian_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guardian_proto_rawDesc), len(file_guardian_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_guardian_proto_goTypes,
		DependencyIndexes: file_guardian_proto_depIdxs,
		MessageInfos:      file_guardian_proto_msgTypes,
	}.Build()
	File_guardian_proto = out.File
	file_guardian_proto_goTypes = nil
	file_guardian_proto_depIdxs = nil
}
