name: Agent CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'agent/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'agent/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: cd agent && go build -v ./

    - name: Test
      run: cd agent && go test -v ./
